CREATE DATABASE IF NOT EXISTS VendasJogos;
USE VendasJogos;

-- Tabela CLIENTES
CREATE TABLE CLIENTES (
    ID_CLIENTES INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(200),
    EMAIL VARCHAR(200) NOT NULL UNIQUE KEY,
    CELULAR VARCHAR(15) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    USUARIO VARCHAR(70) NOT NULL,
    SENHA VARCHAR(255) NOT NULL UNIQUE KEY
);
/*
ATUALIZAÇÃO(05/03/2026): Tabela de produtos
- alterado o tipo da coluna descricao de: varchar(255) -> text.
- adicionado 'NOT NULL' nas seguintes colunas: tamanho, descricao, classificacao_indicativa. 
*/
-- Tabela PRODUTOS
CREATE TABLE PRODUTOS (
    ID_PRODUTOS INT AUTO_INCREMENT PRIMARY KEY,
    NOME_DO_JOGO VARCHAR(200),
    CATEGORIA VARCHAR(200) NOT NULL,
    CLASSIFICACAO_INDICATIVA VARCHAR(30) NOT NULL,
    PRECO DECIMAL(5,2) NOT NULL,
    TAMANHO VARCHAR(200) NOT NULL,
    DESCRICAO TEXT not null,
    FOTO_CAPA TEXT NOT NULL,
    FOTO1 TEXT NOT NULL,
    FOTO2 TEXT NOT NULL,
    FOTO3 TEXT NOT NULL,
    FOTO4 TEXT NOT NULL,
    FOTO5 TEXT NOT NULL,
    FOTO6 TEXT NOT NULL,
    FOTO7 TEXT NOT NULL,
    VIDEO TEXT
);

/*
ATUALIZAÇÃO(03/05/2026): Tabela de vendas
	removidos os itens da tabela: id_clientes, id_produtos, quantidade, preco_unitario, 
*/
-- Tabela VENDAS
CREATE TABLE VENDAS (
    ID_VENDAS INT AUTO_INCREMENT PRIMARY KEY,
    DATAS DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    STATUS_PAGAMENTO ENUM('PAGO','PENDENTE','CANCELADO','EM PROCESSAMENTO'),
    METODO_PAGAMENTO ENUM('CRÉDITO','PIX'),
    TOTAL DECIMAL(10,2) NOT NULL
    -- FOREIGN KEY (ID_CLIENTES) REFERENCES CLIENTES(ID_CLIENTES),
    -- FOREIGN KEY (ID_PRODUTOS) REFERENCES PRODUTOS(ID_PRODUTOS)
	-- HORA TIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    -- QUANTIDADE INT NOT NULL,
    -- ID_CLIENTES INT NOT NULL,
	-- ID_PRODUTOS INT NOT NULL,
);

/*
ATUALIZAÇÃO(03/05/2026): Adicionar uma nova tabela chamada de 'vendas_detalhes'
	Itens da tabela: id_vendas_detalhes, id_vendas, id_clientes, id_produtos, quantidade, preco_unitario, 
*/
CREATE TABLE ITENS_VENDAS(
	id_vendas_detalhes INT AUTO_INCREMENT PRIMARY KEY, 
	quantidade INT NOT NULL, 
	preco_unitario DECIMAL NOT NULL,
	TOTAL DECIMAL(10,2) NOT NULL,
    ID_VENDAS INT NOT NULL,
    ID_CLIENTES INT NOT NULL,
    ID_PRODUTOS INT NOT NULL
-- FOREIGN KEY (ID_VENDAS) REFERENCES VENDAS(ID_VENDAS), 
-- foreign key (id_clientes) REFERENCES CLIENTES(ID_CLIENTES), 
-- foreign key (id_produtos) references PRODUTOS(ID_PRODUOS) 
);


-- Tabela ESTOQUES
CREATE TABLE ESTOQUES (
    ID_ESTOQUES INT AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUTOS INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    DATA_ENTRADA DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_PRODUTOS) REFERENCES PRODUTOS(ID_PRODUTOS)
);

-- Tabela EXTRAS
CREATE TABLE EXTRAS (
    ID_EXTRAS INT AUTO_INCREMENT PRIMARY KEY,
    NOME_DO_EXTRA VARCHAR(200),
    ID_PRODUTOS INT NOT NULL,
    FOREIGN KEY (ID_PRODUTOS) REFERENCES PRODUTOS(ID_PRODUTOS)
);

-- Tabela REQUISITOS
CREATE TABLE REQUISITOS (
    ID_REQUISITO INT AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUTOS INT NOT NULL,
    PROCESSADOR VARCHAR(100) NOT NULL,
    MEMORIA_RAM VARCHAR(50),
    SISTEMA_OPERACIONAL VARCHAR(100) NOT NULL,
    PLACA_DE_VIDEO VARCHAR(150) NOT NULL,
    ARMAZENAMENTO VARCHAR(50),
    VERSAO_DIRECTX VARCHAR(30),
    CONEXAO_INTERNET ENUM('SIM','NÃO'),
    OUTROS VARCHAR(255),
    FOREIGN KEY (ID_PRODUTOS) REFERENCES PRODUTOS(ID_PRODUTOS)
);
ALTER TABLE `dbVendasJogos`.`itens_vendas` 
ADD CONSTRAINT `fk_itens_vendas_pk_vendas`
  FOREIGN KEY (`id_vendas`)
  REFERENCES `dbVendasJogos`.`vendas` (`id_vendas`)
  
