CREATE DATABASE IF NOT EXISTS VendasJogos;
USE VendasJogos;

-- Tabela CLIENTES
CREATE TABLE CLIENTES (
    ID_CLIENTES INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(200),
    EMAIL VARCHAR(200) NOT NULL UNIQUE KEY,
    CELULAR VARCHAR(15) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    USUARIO VARCHAR(70) NOT NULL,
    SENHA VARCHAR(255) NOT NULL UNIQUE KEY
);

-- Tabela PRODUTOS
CREATE TABLE PRODUTOS (
    ID_PRODUTOS INT AUTO_INCREMENT PRIMARY KEY,
    NOME_DO_JOGO VARCHAR(200),
    CATEGORIA VARCHAR(200) NOT NULL,
    CLASSIFICACAO_INDICATIVA VARCHAR(30),
    PRECO DECIMAL(5,2) NOT NULL,
    TAMANHO VARCHAR(200),
    DESCRICAO VARCHAR(255)
);

-- Tabela VENDAS
CREATE TABLE VENDAS (
    ID_VENDAS INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTES INT NOT NULL,
    ID_PRODUTOS INT NOT NULL,
    DATAS DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    -- HORA TIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    QUANTIDADE INT NOT NULL,
    STATUS_PAGAMENTO ENUM('PAGO','PENDENTE','CANCELADO','EM PROCESSAMENTO'),
    METODO_PAGAMENTO ENUM('CRÉDITO','PIX'),
    TOTAL DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (ID_CLIENTES) REFERENCES CLIENTES(ID_CLIENTES),
    FOREIGN KEY (ID_PRODUTOS) REFERENCES PRODUTOS(ID_PRODUTOS)
);




-- Tabela ESTOQUES
CREATE TABLE ESTOQUES (
    ID_ESTOQUES INT AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUTOS INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    DATA_ENTRADA DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_PRODUTOS) REFERENCES PRODUTOS(ID_PRODUTOS)
);

-- Tabela EXTRAS
CREATE TABLE EXTRAS (
    ID_EXTRAS INT AUTO_INCREMENT PRIMARY KEY,
    NOME_DO_EXTRA VARCHAR(200),
    ID_PRODUTOS INT NOT NULL,
    FOREIGN KEY (ID_PRODUTOS) REFERENCES PRODUTOS(ID_PRODUTOS)
);

-- Tabela REQUISITOS
CREATE TABLE REQUISITOS (
    ID_REQUISITO INT AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUTOS INT NOT NULL,
    PROCESSADOR VARCHAR(100) NOT NULL,
    MEMORIA_RAM VARCHAR(50),
    SISTEMA_OPERACIONAL VARCHAR(100) NOT NULL,
    PLACA_DE_VIDEO VARCHAR(150) NOT NULL,
    ARMAZENAMENTO VARCHAR(50),
    VERSAO_DIRECTX VARCHAR(30),
    CONEXAO_INTERNET ENUM('SIM','NÃO'),
    OUTROS VARCHAR(255),
    FOREIGN KEY (ID_PRODUTOS) REFERENCES PRODUTOS(ID_PRODUTOS)
);